### PR TITLE
Guest Registration Enable / Disable

### PR DESCRIPTION
**Pull request by AndyD328**
Thanks Matt.

I think the contrib notes are good, I just hadn't come across them. Is there a way of easily updating the note at the bottom of each page
"Found errors? Think you can improve this documentation? edit this page" to include a link to https://docs.drupalcommerce.org/introduction/contribute ?

### CODE REVIEW

**Comment by mglaman** [comment]
comment to kick off build.

**Comment by mglaman** [comment]
@AndyD328 Oh, interesting. I had no idea there was a patch to allow registration _after_ checkout. I was refering to the Login pane which has the `allow_registration` option. If you disable guest checkout you can force them to register.

https://github.com/drupalcommerce/commerce/blob/8.x-2.x/modules/checkout/src/Plugin/Commerce/CheckoutPane/Login.php#L145

This was the initial intent. However, I would not mind keeping mention of the proposed pane at the bottom of the sec.

**Comment by AndyD328** [comment]
It is interesting, I've never unchecked the guest checkout box before, it makes a lot of sense to have those options. 
I'll try and add the main content tomorrow but it might not happen until next week.

**Comment by AndyD328** [comment]
Hi Matt,

I filled out the register at checkout section and redid the control guest checkout section.  

Also added some Buyer screenshots to show how it affected the checkout display. Happy to remove if you don't like them.

Cheers!

**Comment by mglaman** [comment]
One nit:

> Allow guests to create an account at the end of the checkout process

This section is on Controlling guest checkout when it should probably be on Allow registration at checkout.

And maybe with "Allow registration at checkout" we replace "at" with "in" or "during"

**Comment by AndyD328** [comment]
Thanks Matt.

- Text & an image moved to from section 2 to 3
- Typos tidied
- Some rewording for clarity

**Comment by mglaman** [comment]
@AndyD328 this looks great. Committed one fix on your branch s/`!At`/`! At` so it highlights properl.

**Pull request merged**
