### PR TITLE
Product catalog first steps

### PR DESCRIPTION
**Pull request by subhojit777**

### CODE REVIEW

**Comment by mglaman** [comment]
@subhojit777 I'll review more, but I'm almost okay with just merging as is unless you have some larger follow ups

**Comment by joshmiller83** [comment]
Looking nice!

**Comment by subhojit777** [comment]
I will start working on them.

**Comment by subhojit777** [comment]
@mglaman @bojanz I have added steps for adding facets as well. "Product catalog setup wiki" is done. Let me know if any improvement can be done.

Next I will be working on "Customize the add to cart form" wiki.

**Comment by mglaman** [comment]
Thanks, @subhojit777. going to merge and we can follow up any adjustments in new PRs.

**Comment by BhagiLimbu** [comment]
Thank you @subhojit777  and @mglaman, It is a big advantage like me who is learning from scratch.

**Pull request merged**
