### PR TITLE
Update docs.md

### PR DESCRIPTION
**Pull request by kaa4ever**
Added Part 1 of new offsite payment gateway: Configuration

### CODE REVIEW

**Comment by mglaman** [comment]
@kaa4ever thanks! going to review :)

**Comment by mglaman** [comment]
@kaa4ever found one problem. The images are broken :/ I can download and add later, or you could visit https://github.com/kaa4ever/commerce-docs/tree/patch-4/user/pages/03.commerce2/02.developer-guide/05.payments/07.off-site-redirect-gateways and click "Upload".

commerce-docs_user_pages_03_commerce2_02_developer-guide_05_payments_07_off-site-redirect-gateways_at_patch-4_ _kaa4ever_commerce-docs

**Comment by kaa4ever** [comment]
@mglaman welcome :) I've now uploaded the images instead of storing them external.

**Comment by mglaman** [comment]
@kaa4ever this is beautiful, thanks so much!

**Pull request merged**
