### PR TITLE
100 update payment gateway list

### PR DESCRIPTION
**Pull request by saurabh-vijayvargiya**
@joshmiller83 @mglaman Need review for PR.

### CODE REVIEW

**Comment by mglaman** [comment]
@saurabh-vijayvargiya thanks! I might do some local tweaking before commit. I don't think we need to include number of users in documentation because it can become stale. The Ludwig can be just a Yes/Pending/Not needed (and if pending make it a link versus full URL.)

I think we can exclude RC1 ready, as this is just a transition period at the moment.

Maybe we can include some kind of description instead. It'd be great to see what other platform documentation does.

**Comment by bojanz** [comment]
I don't think we should have a Ludwig column either, for the same reason as the RC1 column.
Any module without Ludwig integration has a bug that needs to be fixed.

**Comment by saurabh-vijayvargiya** [comment]
@mglaman @bojanz Changes made as per suggestions. Number of users removed, ludwig column, RC1 column also removed. Added description column.

Please review.

**Comment by joshmiller83** [comment]
Please remove the machine names and fix the padding issues in the first column

**Comment by mglaman** [comment]
Should we keep the version numbers? This could get dated very fast.

**Comment by joshmiller83** [comment]
And remove the version numbers. Let's make it as evergreen as we can.

**Comment by saurabh-vijayvargiya** [comment]
@mglaman @joshmiller83 Version number and machine name removed. And padding issue is also resolved. Needs review

**Comment by mglaman** [comment]
Thanks for the final changes!

**Pull request merged**
