### PR TITLE
Document what happened to most Rules.

### PR DESCRIPTION
**Pull request by wizonesolutions**
This an initial attempt at this. I think it contains enough detail that a developer audience should be able to search through the code or UI (in the case of payment gateways) and figure out what to do from there. I could _perhaps_ say a bit more about how to add new payment gateway conditions, but I think that should be documented elsewhere and perhaps linked to from here, like resolvers.

### CODE REVIEW

**Comment by mglaman** [comment]
Hm. I'm trying to figure out why Platform.sh didn't build.

**Comment by wizonesolutions** [comment]
@mglaman Made the requested changes. I should note that I wasn't sure of the best way to do the "more on resolvers" link at the bottom. Maybe it should be relative or use file slugs or whatever so that it won't be too fragile, but I figured this was Good Enough to start. We probably aren't restructuring for a while since you specifically spent some time building the structure/outline.

**Comment by mglaman** [comment]
I think that's fine for now. It can link to overview and all the others.
Maybe we should drop a `@todo proper links and additional links` comment.

**Comment by mglaman** [comment]
@wizonesolutions I'm ready to merge; but I'll let you 👍 or 👎 that decision, in case you have more incoming.

**Comment by wizonesolutions** [comment]
👍

I just wanted to get it started to organize my thoughts for my presentation :)

I might add more in a couple weeks as I get farther along, but no need to hold this up. More pull requests can always be rolled!

**Comment by mglaman** [comment]
Thanks for this!

**Pull request merged**
