### PR TITLE
Managing Order Payments

### PR DESCRIPTION
**Pull request by shabananavas**
Issue 101

### CODE REVIEW

**Comment by mglaman** [comment]
I don't like that this shows editing an order. I feel it should just show:

* Voiding an authorization
* Capturing an authorization
* Refunding a captured payment.

**Comment by mglaman** [comment]
@krcha can you manually port this into the GravCMS setup? I don't think we have this documentation yet.

**Comment by krcha** [comment]
@mglaman done

**Comment by mglaman** [comment]
Thanks, @krcha !

**Pull request closed without merging**
