### PR TITLE
106 create product type

### PR DESCRIPTION
**Pull request by saurabh-vijayvargiya**
Pull request for create product type

### CODE REVIEW

**Comment by saurabh-vijayvargiya** [comment]
@mglaman Review needed for this P.R.

**Comment by mglaman** [comment]
@saurabh-vijayvargiya yay, thanks! However, I just realized the screenshots have security warnings in them.

**Comment by saurabh-vijayvargiya** [comment]
@mglaman Should I post new images without those errors ?

**Comment by smmccabe** [comment]
@saurabh-vijayvargiya yes please, makes it look more professional.

**Comment by saurabh-vijayvargiya** [comment]
@mglaman @joshmiller83 @smmccabe New images uploaded. Needs review.

**Pull request merged**
